baseURL = 'https://www.qader.dev/blog'
languageCode = 'en-us'
title = 'D0WN$AMPLED'
theme = 'archie'
copyright = "© ahmad ©"

[params]
	mode="toggle" 
	useCDN=true 
	mathjax = true 
	katex = true 





[[menu.main]]
  name = "Homepage"
  url = "https://www.qader.dev"
  weight = 1

[[menu.main]]
  name = "All Posts"
  url = "/"
  weight = 2


[[menu.main]]
  name = "Beyond The Margins"
  url = "/posts/beyondthemargins"
  weight = 3

[[menu.main]]
  name = "Within The Margins"
  url = "/posts/withinthemargins"
  weight = 4


[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/forrealahmad/"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/x4ndri"

