baseURL = 'https://www.qader.dev/blog'
languageCode = 'en-us'
title = 'D0WN$AMPLED'
theme = 'archie'

[[menu.main]]
  name = "Homepage"
  url = "https://www.qader.dev"
  weight = 1

[[menu.main]]
  name = "All Posts"
  url = "/"
  weight = 2


[[menu.main]]
  name = "Beyond The Margins"
  url = "/posts/beyondthemargins"
  weight = 3

[[menu.main]]
  name = "Within The Margins"
  url = "/posts/withinthemargins"
  weight = 4
